In [20]:
import counts
import pandas as pd
import os

In [21]:
pids = counts.parse_patric_gff(gff)

NC_010554.1	PATRIC	transcript	458478	458597	.	+	0	ID=fig|529507.6.rna.12

NC_010554.1	PATRIC	pseudogene	2362891	2363369	.	+	0	ID=fig|529507.6.pg.1

NC_010554.1	PATRIC	transcript	2448667	2448786	.	-	0	ID=fig|529507.6.rna.55

NC_010554.1	PATRIC	transcript	3032247	3032366	.	-	0	ID=fig|529507.6.rna.64

NC_010554.1	PATRIC	transcript	3343540	3343659	.	-	0	ID=fig|529507.6.rna.71

NC_010554.1	PATRIC	transcript	3575239	3575358	.	+	0	ID=fig|529507.6.rna.78

NC_010554.1	PATRIC	transcript	3575524	3575643	.	+	0	ID=fig|529507.6.rna.80

NC_010554.1	PATRIC	transcript	3611814	3611933	.	+	0	ID=fig|529507.6.rna.89

NC_010554.1	PATRIC	transcript	3882107	3882226	.	+	0	ID=fig|529507.6.rna.105

In [22]:
# 4 hour time point
cf = "/Users/annasintsova/git_repos/spatial_dynamics_of_gene_expression_in_response_to_T6SS_attack/data/counts/reverse/"
gff = "/Users/annasintsova/git_repos/spatial_dynamics_of_gene_expression_in_response_to_T6SS_attack/data/ref/HI4320_PATRIC.gff"

In [23]:
tpms = counts.normalize_counts_to_tpm(cf, gff)
df = pd.DataFrame.from_dict(tpms)
tags = []
for f in df.index:
    try:
        tag = pids[f]
    except KeyError:
        tag = f
    tags.append(tag)
df["tags"] = tags
df = df.set_index("tags")

fn = os.path.join(os.path.dirname(cf), "TPMs.csv")
df.to_csv(fn)

df.head()

,77464,76068,76082,63632,76076,77466,63638,76088,76074,76080,...,63639,76089,76087,76073,76079,77463,76067,76071,63635,76085
tags,,,,,,,,,,,,,,,,,,,,,
PMI0001,82.104925,65.181479,104.117060,113.945252,47.807872,118.036881,125.444096,50.810361,63.255331,61.457083,...,144.720633,59.860450,91.834036,82.879744,72.478302,104.789927,66.864376,46.332196,134.932404,32.307047
PMI0010,42.315562,102.361338,245.406274,717.590266,53.141216,66.241811,762.584114,88.598827,86.321206,247.921000,...,692.952270,109.115527,134.769571,72.451028,221.323370,61.305298,202.083493,92.576546,552.610174,174.830607
PMI0102,411.437468,439.238672,348.268872,39.762120,413.081521,250.408605,36.552635,300.812995,512.889924,364.671790,...,32.802474,327.346580,286.126166,492.560834,258.605690,460.261317,346.188770,439.936406,33.477393,286.901509
PMI1034,393.938571,251.030362,559.203778,1137.007267,285.098739,381.940782,1024.868359,525.634824,336.737925,509.491330,...,796.611352,476.163633,516.150681,308.986956,491.912376,368.442300,386.172785,375.769437,846.209219,449.820049
PMI1035,2346.635802,1050.689286,1952.581639,7445.746579,949.425508,1669.764001,6302.826720,2022.822770,1140.475563,1727.468018,...,5725.194389,1478.386256,1992.994747,1275.497386,1798.436803,1874.998973,1165.640083,1953.298165,6207.269929,2272.039260

In [24]:
# 30 min time point 
cf = "/Users/annasintsova/git_repos/spatial_dynamics_of_gene_expression_in_response_to_T6SS_attack/data/counts/stranded/"

In [25]:
tpms = counts.normalize_counts_to_tpm(cf, gff)
df = pd.DataFrame.from_dict(tpms)
tags = []
for f in df.index:
    try:
        tag = pids[f]
    except KeyError:
        tag = f
    tags.append(tag)
df["tags"] = tags
df = df.set_index("tags")
fn = os.path.join(os.path.dirname(cf), "TPMs.csv")
df.to_csv(fn)

df.head()

,77464,76068,76082,63632,76076,77466,63638,76088,76074,76080,...,63639,76089,76087,76073,76079,77463,76067,76071,63635,76085
tags,,,,,,,,,,,,,,,,,,,,,
PMI0001,225.617013,123.248164,186.265234,13.550976,125.740132,297.945990,15.129376,128.488353,223.027720,155.400364,...,24.986055,197.939393,198.391039,234.272033,137.348754,314.464114,171.251128,161.191617,4.678828,86.543101
PMI0010,98.889717,348.029120,429.029482,26.399352,188.289639,116.600109,45.848934,328.916725,310.663801,489.868953,...,40.563849,238.330153,355.215602,238.103856,436.050053,165.860869,500.657999,357.915537,77.646847,347.609860
PMI0102,59.124402,63.344614,71.295083,472.931988,86.187964,66.092595,459.497013,55.442603,77.400316,61.040386,...,540.851314,60.630770,60.483589,74.831981,55.861146,64.997047,61.289636,87.951757,901.638309,47.665830
PMI1034,1505.727214,1111.035154,1521.177432,19.011429,1338.485168,1212.183057,40.522087,1948.213130,1448.753375,1735.783957,...,29.875864,1773.723825,1813.748522,1048.872586,1878.953609,1222.840297,1188.614201,1557.029753,35.804680,2066.468872
PMI1035,9487.283065,8280.664327,9536.431238,147.878029,7172.807875,9031.371845,473.294326,11224.056699,7790.996853,8453.024344,...,113.610779,8768.239267,9229.119071,6370.777720,10477.386647,8822.419538,6699.717651,13030.573097,329.045246,10569.824975